### ISSUE TITLE
Hamburger menu in mobile view

### ISSUE THREAD

**Issue by michass** [EdddieN/machinon-domoticz_theme#121]
Please set  hamburger menu to automaticly close after choose tab

**Comment by DewGew** [comment]
Not yet fixed..

**Comment by EdddieN** [comment]
This is working for me now, even on mobile device

**Comment by michass** [comment]
https://photos.app.goo.gl/t1nTBUsDFh2bVr14A
Maybe i wrote something wrong, but hamburger main menu don't disapear after use

**Comment by DewGew** [comment]
You have to use beta branch

**Comment by bartplessers** [comment]
sorry to spoil the party, but I still have this bug...
running Machinon theme V.1.10.2

**Comment by davidlb** [comment]
@bartplessers please update to latest beta, I fixed it few days ago

**Comment by bartplessers** [comment]
Hi @davidlb 
Unfortunatly, the only tabs that hide the hamburger are "Domoticz" and "Settings":

![12-12-2019 21-06-22](https://user-images.githubusercontent.com/10470708/70746627-72310780-1d26-11ea-9214-af950959e004.png)


All the other menu items do not collapse the menu.


Running 
- Machinon theme V.1.12 beta 
- WIN 10 1909 64bits
- cleared cache from browser
- reset theme settings
- anonymous browsing


It works correctly only
- chromium Version 80.0.3960.0 (Developer Build) (64-bit)
- firefox 71.0 (64-bits)
- Edge

It does NOT work correct on
- chrome 78.0.3904.108 64bit
- Edge Beta Version 79.0.309.47 (Official build) beta (64-bit)

It DOES work correct on the above browsers if you **start** with a mobile view (small window size of browser), if you start with a large window and decrease the size so that the menu becomes mobile afterwards, than the menu collapse not anymore...


Kind regards,
Bart

**Comment by davidlb** [comment]
Thanks @bartplessers for your detailed feedback, I'll check it

**Comment by bartplessers** [comment]
@davidlb: super! works as a charm now!
