### ISSUE TITLE
Theme is calling 'checkauth()' every time

### ISSUE THREAD

**Issue by davidlb** [EdddieN/machinon-domoticz_theme#284]
This is not needed, it seems to make the temperature widgets scrolling info to hickup as well...
The 'admin rights' is already in the rootScope which you can already access

Reported by gizmocuz in domoticz/domoticz#3302

**Comment by DewGew** [comment]
This is because we want to get adminrights when hide/show buttons in navigation if user is admin or not.
https://github.com/EdddieN/machinon-domoticz_theme/blob/b42e9c9c30d814c6de8b3790bb217db538691fd8/custom.js#L130
https://github.com/EdddieN/machinon-domoticz_theme/blob/b42e9c9c30d814c6de8b3790bb217db538691fd8/custom.js#L178

maybe there is a simplier way.

**Comment by davidlb** [comment]
Guys, can you update to latest beta?
I rewrote checkauth without ajax call, removed getstatus calls and removed autoscroll for global performance improvement. Well, it seems but I need your feedback :)

**Comment by chrislader** [comment]
@davidlb just updated to latest beta domoticz (915) + latest beta machinon theme.

A LOT better now. For me this is fixed. Page loads quite fast now.

Want me to check some specific logs?

**Comment by davidlb** [comment]
@chrislader thansk for your feedback!
